/**
 * Seed script for Big Idea 3: Part 3 (Topics 3.9-3.13)
 * Run with: node server/seeds/bigIdea3-part3.js
 */

const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '../../.env') });
const { db } = require('../firebase');

if (process.env.FIREBASE_PROJECT_ID !== 'ap-csp-mastery') {
  console.error(`ERROR: Wrong project!`);
  process.exit(1);
}

const topics = [
  {
    id: 'aap-3-9',
    bigIdeaId: 'big-idea-3',
    name: '3.9 Developing Algorithms',
    description: 'Algorithms can be created from an idea, by combining existing algorithms, or by modifying existing algorithms.',
    order: 9,
    learningObjectives: ['AAP-2.L', 'AAP-2.M']
  },
  {
    id: 'aap-3-10',
    bigIdeaId: 'big-idea-3',
    name: '3.10 Lists',
    description: 'Lists are ordered sequences of elements that can be accessed by index.',
    order: 10,
    learningObjectives: ['AAP-2.N', 'AAP-2.O']
  },
  {
    id: 'aap-3-11',
    bigIdeaId: 'big-idea-3',
    name: '3.11 Binary Search',
    description: 'Binary search is an efficient algorithm for finding elements in a sorted list.',
    order: 11,
    learningObjectives: ['AAP-2.P']
  },
  {
    id: 'aap-3-12',
    bigIdeaId: 'big-idea-3',
    name: '3.12 Calling Procedures',
    description: 'Procedures are reusable blocks of code that can accept parameters and return values.',
    order: 12,
    learningObjectives: ['AAP-3.A', 'AAP-3.B']
  },
  {
    id: 'aap-3-13',
    bigIdeaId: 'big-idea-3',
    name: '3.13 Developing Procedures',
    description: 'Creating procedures involves defining parameters and return values.',
    order: 13,
    learningObjectives: ['AAP-3.C']
  }
];

const questionsData = {
  'aap-3-9': [
    { text: 'An algorithm is best described as:', type: 'multiple_choice', options: [{ id: 'a', text: 'A programming language' }, { id: 'b', text: 'A step-by-step set of instructions to solve a problem' }, { id: 'c', text: 'A type of computer' }, { id: 'd', text: 'A database' }], correctAnswers: ['b'], explanation: 'An algorithm is a finite set of instructions that accomplish a specific task.' },
    { text: 'Which is a characteristic of a well-designed algorithm?', type: 'multiple_choice', options: [{ id: 'a', text: 'It runs forever' }, { id: 'b', text: 'It produces correct output for valid input' }, { id: 'c', text: 'It uses the most memory possible' }, { id: 'd', text: 'It has no steps' }], correctAnswers: ['b'], explanation: 'Good algorithms produce correct results for all valid inputs.' },
    { text: 'Two algorithms that produce the same result are called:', type: 'multiple_choice', options: [{ id: 'a', text: 'Identical' }, { id: 'b', text: 'Equivalent' }, { id: 'c', text: 'Parallel' }, { id: 'd', text: 'Sequential' }], correctAnswers: ['b'], explanation: 'Equivalent algorithms produce the same output for the same input.' },
    { text: 'What is the first step in developing an algorithm?', type: 'multiple_choice', options: [{ id: 'a', text: 'Write the code' }, { id: 'b', text: 'Understand the problem' }, { id: 'c', text: 'Test the solution' }, { id: 'd', text: 'Choose a programming language' }], correctAnswers: ['b'], explanation: 'Understanding the problem is essential before developing a solution.' },
    { text: 'Finding the maximum value in a list requires:', type: 'multiple_choice', options: [{ id: 'a', text: 'Sorting the list first' }, { id: 'b', text: 'Comparing each element to track the largest' }, { id: 'c', text: 'Adding all elements' }, { id: 'd', text: 'Removing duplicates' }], correctAnswers: ['b'], explanation: 'Track the maximum by comparing each element to the current max.' },
    { text: 'What is pseudocode?', type: 'multiple_choice', options: [{ id: 'a', text: 'Actual executable code' }, { id: 'b', text: 'A human-readable description of an algorithm' }, { id: 'c', text: 'Machine code' }, { id: 'd', text: 'Encrypted code' }], correctAnswers: ['b'], explanation: 'Pseudocode describes algorithms in plain language, not actual code.' },
    { text: 'An algorithm to find the sum of numbers 1 to n uses:', type: 'multiple_choice', options: [{ id: 'a', text: 'Only conditionals' }, { id: 'b', text: 'Iteration or a formula' }, { id: 'c', text: 'Only variables' }, { id: 'd', text: 'No operations' }], correctAnswers: ['b'], explanation: 'Sum can be found by iterating and adding, or using n*(n+1)/2.' },
    { text: 'What is algorithm efficiency?', type: 'multiple_choice', options: [{ id: 'a', text: 'How correct an algorithm is' }, { id: 'b', text: 'How fast an algorithm runs relative to input size' }, { id: 'c', text: 'How many variables it uses' }, { id: 'd', text: 'How many lines of code it has' }], correctAnswers: ['b'], explanation: 'Efficiency measures time and space usage as input grows.' },
    { text: 'To count occurrences of a value in a list, you need:', type: 'multiple_choice', options: [{ id: 'a', text: 'A counter variable and iteration' }, { id: 'b', text: 'Only a conditional' }, { id: 'c', text: 'Sorting first' }, { id: 'd', text: 'No loops' }], correctAnswers: ['a'], explanation: 'Iterate through the list, incrementing a counter when the value matches.' },
    { text: 'What is a logic error?', type: 'multiple_choice', options: [{ id: 'a', text: 'A syntax mistake' }, { id: 'b', text: 'An error in the algorithm that produces wrong results' }, { id: 'c', text: 'A hardware failure' }, { id: 'd', text: 'A spelling error' }], correctAnswers: ['b'], explanation: 'Logic errors cause incorrect behavior even though code runs.' },
    { text: 'Testing an algorithm with edge cases means:', type: 'multiple_choice', options: [{ id: 'a', text: 'Testing with average inputs' }, { id: 'b', text: 'Testing with extreme or boundary inputs' }, { id: 'c', text: 'Not testing at all' }, { id: 'd', text: 'Testing only once' }], correctAnswers: ['b'], explanation: 'Edge cases test boundaries like empty lists, zero, or maximum values.' },
    { text: 'Which helps identify algorithm errors?', type: 'multiple_select', options: [{ id: 'a', text: 'Tracing through code manually' }, { id: 'b', text: 'Testing with multiple inputs' }, { id: 'c', text: 'Code review' }, { id: 'd', text: 'Ignoring output' }], correctAnswers: ['a', 'b', 'c'], explanation: 'Tracing, testing, and review all help find errors.' },
    { text: 'To swap two values without a third variable:', type: 'multiple_choice', options: [{ id: 'a', text: 'Is impossible' }, { id: 'b', text: 'Use arithmetic operations (with limitations)' }, { id: 'c', text: 'Delete both values' }, { id: 'd', text: 'Use a loop' }], correctAnswers: ['b'], explanation: 'a = a + b; b = a - b; a = a - b swaps values (with overflow risk).' },
    { text: 'Breaking a problem into smaller parts is called:', type: 'multiple_choice', options: [{ id: 'a', text: 'Iteration' }, { id: 'b', text: 'Decomposition' }, { id: 'c', text: 'Compilation' }, { id: 'd', text: 'Encryption' }], correctAnswers: ['b'], explanation: 'Decomposition breaks complex problems into manageable subproblems.' },
    { text: 'What is debugging?', type: 'multiple_choice', options: [{ id: 'a', text: 'Adding new features' }, { id: 'b', text: 'Finding and fixing errors' }, { id: 'c', text: 'Deleting code' }, { id: 'd', text: 'Writing documentation' }], correctAnswers: ['b'], explanation: 'Debugging is the process of identifying and correcting errors.' },
    { text: 'An off-by-one error typically occurs in:', type: 'multiple_choice', options: [{ id: 'a', text: 'Variable declarations' }, { id: 'b', text: 'Loop boundaries' }, { id: 'c', text: 'Comments' }, { id: 'd', text: 'Procedure names' }], correctAnswers: ['b'], explanation: 'Off-by-one errors happen when loops iterate one too many/few times.' },
    { text: 'Algorithm verification ensures:', type: 'multiple_choice', options: [{ id: 'a', text: 'Code compiles' }, { id: 'b', text: 'The algorithm correctly solves the problem' }, { id: 'c', text: 'Variables are named correctly' }, { id: 'd', text: 'Code is short' }], correctAnswers: ['b'], explanation: 'Verification confirms the algorithm meets its specification.' },
    { text: 'What is a flowchart?', type: 'multiple_choice', options: [{ id: 'a', text: 'Executable code' }, { id: 'b', text: 'A visual representation of an algorithm' }, { id: 'c', text: 'A type of loop' }, { id: 'd', text: 'A data structure' }], correctAnswers: ['b'], explanation: 'Flowcharts use shapes and arrows to visualize algorithm flow.' },
    { text: 'Combining existing algorithms to solve a new problem is:', type: 'multiple_choice', options: [{ id: 'a', text: 'Impossible' }, { id: 'b', text: 'A common and effective approach' }, { id: 'c', text: 'Always wrong' }, { id: 'd', text: 'Called compilation' }], correctAnswers: ['b'], explanation: 'Building on existing algorithms is efficient and reduces errors.' },
    { text: 'What is incremental development?', type: 'multiple_choice', options: [{ id: 'a', text: 'Writing all code at once' }, { id: 'b', text: 'Building and testing small pieces progressively' }, { id: 'c', text: 'Deleting code incrementally' }, { id: 'd', text: 'Running code faster' }], correctAnswers: ['b'], explanation: 'Incremental development builds functionality in small, testable pieces.' },
    { text: 'A syntax error is:', type: 'multiple_choice', options: [{ id: 'a', text: 'A logic mistake' }, { id: 'b', text: 'A violation of programming language rules' }, { id: 'c', text: 'A runtime crash' }, { id: 'd', text: 'An efficient algorithm' }], correctAnswers: ['b'], explanation: 'Syntax errors occur when code violates language grammar rules.' },
    { text: 'Which represents correct algorithm design order?', type: 'multiple_choice', options: [{ id: 'a', text: 'Code, then plan' }, { id: 'b', text: 'Plan, implement, test, debug' }, { id: 'c', text: 'Test, then write' }, { id: 'd', text: 'Debug first' }], correctAnswers: ['b'], explanation: 'Good development follows: plan, implement, test, debug cycle.' },
    { text: 'Hand-tracing an algorithm means:', type: 'multiple_choice', options: [{ id: 'a', text: 'Writing code by hand' }, { id: 'b', text: 'Manually tracking variable values step by step' }, { id: 'c', text: 'Drawing pictures' }, { id: 'd', text: 'Typing fast' }], correctAnswers: ['b'], explanation: 'Hand-tracing follows code execution to track values and find errors.' },
    { text: 'What is a runtime error?', type: 'multiple_choice', options: [{ id: 'a', text: 'An error during program execution' }, { id: 'b', text: 'A spelling mistake' }, { id: 'c', text: 'A missing variable name' }, { id: 'd', text: 'A compilation warning' }], correctAnswers: ['a'], explanation: 'Runtime errors occur while the program is running.' },
    { text: 'To reverse a list, one approach is:', type: 'multiple_choice', options: [{ id: 'a', text: 'Delete the list' }, { id: 'b', text: 'Swap elements from ends toward middle' }, { id: 'c', text: 'Sort the list' }, { id: 'd', text: 'Add more elements' }], correctAnswers: ['b'], explanation: 'Reversing can swap first/last, second/second-last, etc.' }
  ],
  'aap-3-10': [
    { text: 'What is the index of the first element in an AP CSP list?', type: 'multiple_choice', options: [{ id: 'a', text: '0' }, { id: 'b', text: '1' }, { id: 'c', text: '-1' }, { id: 'd', text: 'Any number' }], correctAnswers: ['b'], explanation: 'AP CSP uses 1-based indexing for lists.' },
    { text: 'If list ← [5, 10, 15, 20], what is list[3]?', type: 'multiple_choice', options: [{ id: 'a', text: '5' }, { id: 'b', text: '10' }, { id: 'c', text: '15' }, { id: 'd', text: '20' }], correctAnswers: ['c'], explanation: 'Index 3 refers to the third element: 15.' },
    { text: 'What does APPEND(list, value) do?', type: 'multiple_choice', options: [{ id: 'a', text: 'Adds value at the beginning' }, { id: 'b', text: 'Adds value at the end' }, { id: 'c', text: 'Removes a value' }, { id: 'd', text: 'Sorts the list' }], correctAnswers: ['b'], explanation: 'APPEND adds an element to the end of a list.' },
    { text: 'After: nums ← [1, 2]; APPEND(nums, 3), what is nums?', type: 'multiple_choice', options: [{ id: 'a', text: '[3, 1, 2]' }, { id: 'b', text: '[1, 2, 3]' }, { id: 'c', text: '[1, 2]' }, { id: 'd', text: '[3]' }], correctAnswers: ['b'], explanation: 'APPEND adds 3 to the end: [1, 2, 3].' },
    { text: 'What does LENGTH(list) return?', type: 'multiple_choice', options: [{ id: 'a', text: 'The last element' }, { id: 'b', text: 'The first element' }, { id: 'c', text: 'The number of elements' }, { id: 'd', text: 'The sum of elements' }], correctAnswers: ['c'], explanation: 'LENGTH returns how many elements are in the list.' },
    { text: 'INSERT(list, 2, value) does what?', type: 'multiple_choice', options: [{ id: 'a', text: 'Inserts value at index 2, shifting others right' }, { id: 'b', text: 'Replaces index 2' }, { id: 'c', text: 'Deletes index 2' }, { id: 'd', text: 'Adds value at the end' }], correctAnswers: ['a'], explanation: 'INSERT places value at index 2 and shifts existing elements.' },
    { text: 'REMOVE(list, 3) does what?', type: 'multiple_choice', options: [{ id: 'a', text: 'Removes the value 3' }, { id: 'b', text: 'Removes element at index 3' }, { id: 'c', text: 'Removes 3 elements' }, { id: 'd', text: 'Clears the list' }], correctAnswers: ['b'], explanation: 'REMOVE deletes the element at the specified index.' },
    { text: 'After: list ← [10, 20, 30]; REMOVE(list, 2), what is list?', type: 'multiple_choice', options: [{ id: 'a', text: '[10, 30]' }, { id: 'b', text: '[20, 30]' }, { id: 'c', text: '[10, 20]' }, { id: 'd', text: '[10, 20, 30]' }], correctAnswers: ['a'], explanation: 'Removing index 2 (value 20) leaves [10, 30].' },
    { text: 'To iterate through all elements of a list, use:', type: 'multiple_choice', options: [{ id: 'a', text: 'An IF statement' }, { id: 'b', text: 'FOR EACH loop' }, { id: 'c', text: 'A single variable' }, { id: 'd', text: 'No loop needed' }], correctAnswers: ['b'], explanation: 'FOR EACH iterates through every element in a list.' },
    { text: 'What is output? list ← [2, 4, 6]; sum ← 0; FOR EACH x IN list {sum ← sum + x}; DISPLAY(sum)', type: 'multiple_choice', options: [{ id: 'a', text: '2' }, { id: 'b', text: '6' }, { id: 'c', text: '12' }, { id: 'd', text: '246' }], correctAnswers: ['c'], explanation: 'Sum: 2 + 4 + 6 = 12.' },
    { text: 'Accessing list[-1] in AP CSP would:', type: 'multiple_choice', options: [{ id: 'a', text: 'Return the last element' }, { id: 'b', text: 'Cause an error' }, { id: 'c', text: 'Return the first element' }, { id: 'd', text: 'Return 0' }], correctAnswers: ['b'], explanation: 'Negative indices are not valid in AP CSP pseudocode.' },
    { text: 'If data ← [1, 2, 3, 4, 5], what is data[LENGTH(data)]?', type: 'multiple_choice', options: [{ id: 'a', text: '1' }, { id: 'b', text: '5' }, { id: 'c', text: '4' }, { id: 'd', text: 'Error' }], correctAnswers: ['b'], explanation: 'LENGTH(data) = 5, and data[5] = 5 (the last element).' },
    { text: 'To find if a value exists in a list:', type: 'multiple_choice', options: [{ id: 'a', text: 'Check only the first element' }, { id: 'b', text: 'Iterate and compare each element' }, { id: 'c', text: 'Use LENGTH' }, { id: 'd', text: 'Use APPEND' }], correctAnswers: ['b'], explanation: 'Linear search compares each element to find a match.' },
    { text: 'What is output? nums ← [5, 10]; nums[1] ← 7; DISPLAY(nums)', type: 'multiple_choice', options: [{ id: 'a', text: '[7, 10]' }, { id: 'b', text: '[5, 7]' }, { id: 'c', text: '[5, 10, 7]' }, { id: 'd', text: '[7, 5, 10]' }], correctAnswers: ['a'], explanation: 'nums[1] ← 7 replaces the first element.' },
    { text: 'After: list ← [1, 2, 3]; INSERT(list, 2, 9), what is list?', type: 'multiple_choice', options: [{ id: 'a', text: '[1, 9, 2, 3]' }, { id: 'b', text: '[1, 2, 9, 3]' }, { id: 'c', text: '[9, 1, 2, 3]' }, { id: 'd', text: '[1, 2, 3, 9]' }], correctAnswers: ['a'], explanation: 'INSERT at index 2 shifts 2 and 3 right: [1, 9, 2, 3].' },
    { text: 'An empty list has length:', type: 'multiple_choice', options: [{ id: 'a', text: '0' }, { id: 'b', text: '1' }, { id: 'c', text: '-1' }, { id: 'd', text: 'Undefined' }], correctAnswers: ['a'], explanation: 'An empty list has no elements, so length is 0.' },
    { text: 'To find the minimum value in a list:', type: 'multiple_choice', options: [{ id: 'a', text: 'Return the first element' }, { id: 'b', text: 'Compare each element to track the smallest' }, { id: 'c', text: 'Return the last element' }, { id: 'd', text: 'Add all elements' }], correctAnswers: ['b'], explanation: 'Iterate through, keeping track of the smallest value seen.' },
    { text: 'What is output? a ← [1, 2]; b ← a; APPEND(b, 3); DISPLAY(LENGTH(a))', type: 'multiple_choice', options: [{ id: 'a', text: '2' }, { id: 'b', text: '3' }, { id: 'c', text: 'Depends on language' }, { id: 'd', text: 'Error' }], correctAnswers: ['c'], explanation: 'Whether b is a copy or reference depends on the language.' },
    { text: 'To calculate the average of numbers in a list:', type: 'multiple_choice', options: [{ id: 'a', text: 'Find the maximum' }, { id: 'b', text: 'Sum all elements and divide by length' }, { id: 'c', text: 'Count the elements only' }, { id: 'd', text: 'Sort the list' }], correctAnswers: ['b'], explanation: 'Average = sum of elements / number of elements.' },
    { text: 'What is output? list ← [10, 20, 30]; FOR EACH x IN list {DISPLAY(x)}', type: 'multiple_choice', options: [{ id: 'a', text: '10' }, { id: 'b', text: '102030' }, { id: 'c', text: '30' }, { id: 'd', text: '60' }], correctAnswers: ['b'], explanation: 'Each element is displayed: 10, then 20, then 30.' },
    { text: 'Accessing an index beyond list length causes:', type: 'multiple_choice', options: [{ id: 'a', text: 'Returns 0' }, { id: 'b', text: 'An error' }, { id: 'c', text: 'Returns empty' }, { id: 'd', text: 'Extends the list' }], correctAnswers: ['b'], explanation: 'Accessing invalid indices causes an index out of bounds error.' },
    { text: 'To remove all occurrences of a value from a list:', type: 'multiple_choice', options: [{ id: 'a', text: 'Call REMOVE once' }, { id: 'b', text: 'Iterate backwards and remove matches' }, { id: 'c', text: 'Use APPEND' }, { id: 'd', text: 'Use LENGTH' }], correctAnswers: ['b'], explanation: 'Iterate backwards to avoid skipping elements when removing.' },
    { text: 'If scores ← [85, 90, 78, 92], which finds the maximum?', type: 'multiple_choice', options: [{ id: 'a', text: 'max ← scores[1]; FOR EACH s IN scores {IF(s > max){max ← s}}' }, { id: 'b', text: 'max ← LENGTH(scores)' }, { id: 'c', text: 'max ← scores[LENGTH(scores)]' }, { id: 'd', text: 'max ← 0' }], correctAnswers: ['a'], explanation: 'Initialize max with first element, update when finding larger.' },
    { text: 'What is output? list ← []; APPEND(list, 5); DISPLAY(LENGTH(list))', type: 'multiple_choice', options: [{ id: 'a', text: '0' }, { id: 'b', text: '1' }, { id: 'c', text: '5' }, { id: 'd', text: 'Error' }], correctAnswers: ['b'], explanation: 'Started empty, added one element, length is 1.' },
    { text: 'Lists are useful for storing:', type: 'multiple_choice', options: [{ id: 'a', text: 'Only numbers' }, { id: 'b', text: 'Only strings' }, { id: 'c', text: 'Collections of related data' }, { id: 'd', text: 'Single values only' }], correctAnswers: ['c'], explanation: 'Lists store collections of related items of various types.' }
  ],
  'aap-3-11': [
    { text: 'Binary search works on:', type: 'multiple_choice', options: [{ id: 'a', text: 'Any list' }, { id: 'b', text: 'Only sorted lists' }, { id: 'c', text: 'Only lists with numbers' }, { id: 'd', text: 'Empty lists' }], correctAnswers: ['b'], explanation: 'Binary search requires a sorted list to function correctly.' },
    { text: 'Binary search is more efficient than linear search when:', type: 'multiple_choice', options: [{ id: 'a', text: 'The list is small' }, { id: 'b', text: 'The list is large and sorted' }, { id: 'c', text: 'The list is unsorted' }, { id: 'd', text: 'Never' }], correctAnswers: ['b'], explanation: 'Binary search shines with large sorted lists, reducing comparisons.' },
    { text: 'Each step of binary search eliminates approximately:', type: 'multiple_choice', options: [{ id: 'a', text: 'One element' }, { id: 'b', text: 'Half the remaining elements' }, { id: 'c', text: 'All elements' }, { id: 'd', text: 'No elements' }], correctAnswers: ['b'], explanation: 'Binary search halves the search space with each comparison.' },
    { text: 'How many comparisons maximum to search 64 elements with binary search?', type: 'multiple_choice', options: [{ id: 'a', text: '64' }, { id: 'b', text: '32' }, { id: 'c', text: '6' }, { id: 'd', text: '7' }], correctAnswers: ['d'], explanation: '2^6 = 64, but we need ceiling of log2(64)+1 = 7 comparisons max.' },
    { text: 'In binary search, you first check the:', type: 'multiple_choice', options: [{ id: 'a', text: 'First element' }, { id: 'b', text: 'Last element' }, { id: 'c', text: 'Middle element' }, { id: 'd', text: 'Random element' }], correctAnswers: ['c'], explanation: 'Binary search starts by checking the middle element.' },
    { text: 'If the target is less than the middle element:', type: 'multiple_choice', options: [{ id: 'a', text: 'Search the right half' }, { id: 'b', text: 'Search the left half' }, { id: 'c', text: 'Stop searching' }, { id: 'd', text: 'Search both halves' }], correctAnswers: ['b'], explanation: 'For sorted ascending, target < middle means search left half.' },
    { text: 'For a list of 1000 elements, binary search needs at most:', type: 'multiple_choice', options: [{ id: 'a', text: '1000 comparisons' }, { id: 'b', text: '500 comparisons' }, { id: 'c', text: '10 comparisons' }, { id: 'd', text: '100 comparisons' }], correctAnswers: ['c'], explanation: 'log2(1000) ≈ 10, so about 10 comparisons maximum.' },
    { text: 'Linear search requires at most n comparisons. Binary search requires:', type: 'multiple_choice', options: [{ id: 'a', text: 'n comparisons' }, { id: 'b', text: 'n/2 comparisons' }, { id: 'c', text: 'log2(n) comparisons' }, { id: 'd', text: '2n comparisons' }], correctAnswers: ['c'], explanation: 'Binary search has logarithmic time complexity.' },
    { text: 'Searching [2, 4, 6, 8, 10] for 6 using binary search first checks:', type: 'multiple_choice', options: [{ id: 'a', text: '2' }, { id: 'b', text: '6' }, { id: 'c', text: '10' }, { id: 'd', text: '4' }], correctAnswers: ['b'], explanation: 'Middle element of 5 items is at index 3, which is 6.' },
    { text: 'If binary search checks middle and finds the target, it:', type: 'multiple_choice', options: [{ id: 'a', text: 'Keeps searching' }, { id: 'b', text: 'Returns the position' }, { id: 'c', text: 'Searches both halves' }, { id: 'd', text: 'Removes the element' }], correctAnswers: ['b'], explanation: 'When the target is found, return its position immediately.' },
    { text: 'Binary search is an example of:', type: 'multiple_choice', options: [{ id: 'a', text: 'Brute force' }, { id: 'b', text: 'Divide and conquer' }, { id: 'c', text: 'Random search' }, { id: 'd', text: 'Linear approach' }], correctAnswers: ['b'], explanation: 'Binary search divides the problem in half at each step.' },
    { text: 'For list [1, 3, 5, 7, 9, 11, 13], searching for 9, how many comparisons?', type: 'multiple_choice', options: [{ id: 'a', text: '1' }, { id: 'b', text: '2' }, { id: 'c', text: '3' }, { id: 'd', text: '4' }], correctAnswers: ['b'], explanation: 'Check 7 (middle), then search right, check 11, then left, find 9 = 2-3 comparisons.' },
    { text: 'If target is not in the list, binary search:', type: 'multiple_choice', options: [{ id: 'a', text: 'Runs forever' }, { id: 'b', text: 'Returns not found after search space is empty' }, { id: 'c', text: 'Returns the middle element' }, { id: 'd', text: 'Crashes' }], correctAnswers: ['b'], explanation: 'When the search space is exhausted, return "not found".' },
    { text: 'Why is sorting a prerequisite for binary search?', type: 'multiple_choice', options: [{ id: 'a', text: 'It makes the list smaller' }, { id: 'b', text: 'It allows eliminating half the elements based on comparison' }, { id: 'c', text: 'It removes duplicates' }, { id: 'd', text: 'It is not actually required' }], correctAnswers: ['b'], explanation: 'Sorted order lets us know which half contains the target.' },
    { text: 'Searching 1 million sorted items with binary search needs at most:', type: 'multiple_choice', options: [{ id: 'a', text: '1 million comparisons' }, { id: 'b', text: '500,000 comparisons' }, { id: 'c', text: 'About 20 comparisons' }, { id: 'd', text: '100 comparisons' }], correctAnswers: ['c'], explanation: 'log2(1,000,000) ≈ 20 comparisons.' },
    { text: 'In binary search, how do you calculate the middle index?', type: 'multiple_choice', options: [{ id: 'a', text: '(low + high) / 2' }, { id: 'b', text: 'low + high' }, { id: 'c', text: 'high - low' }, { id: 'd', text: 'Just use 0' }], correctAnswers: ['a'], explanation: 'Middle = (low + high) / 2 (integer division).' },
    { text: 'Binary search on [10, 20, 30, 40] looking for 25 will:', type: 'multiple_choice', options: [{ id: 'a', text: 'Find it at index 2' }, { id: 'b', text: 'Return not found' }, { id: 'c', text: 'Return 20' }, { id: 'd', text: 'Return 30' }], correctAnswers: ['b'], explanation: '25 is not in the list, so binary search returns not found.' },
    { text: 'Compared to linear search, binary search:', type: 'multiple_choice', options: [{ id: 'a', text: 'Always requires fewer comparisons' }, { id: 'b', text: 'Requires fewer comparisons for large sorted lists' }, { id: 'c', text: 'Works on unsorted lists' }, { id: 'd', text: 'Is always slower' }], correctAnswers: ['b'], explanation: 'Binary search excels with large sorted lists but requires sorting.' },
    { text: 'A phone book search is similar to:', type: 'multiple_choice', options: [{ id: 'a', text: 'Linear search' }, { id: 'b', text: 'Binary search' }, { id: 'c', text: 'No search' }, { id: 'd', text: 'Random search' }], correctAnswers: ['b'], explanation: 'Opening a phone book in the middle and narrowing down is like binary search.' },
    { text: 'If low > high in binary search, it means:', type: 'multiple_choice', options: [{ id: 'a', text: 'Target is found' }, { id: 'b', text: 'Target is not in the list' }, { id: 'c', text: 'Continue searching' }, { id: 'd', text: 'Error in algorithm' }], correctAnswers: ['b'], explanation: 'low > high means search space is empty; target not found.' },
    { text: 'Binary search has time complexity:', type: 'multiple_choice', options: [{ id: 'a', text: 'O(n)' }, { id: 'b', text: 'O(log n)' }, { id: 'c', text: 'O(n²)' }, { id: 'd', text: 'O(1)' }], correctAnswers: ['b'], explanation: 'Binary search runs in O(log n) time.' },
    { text: 'For list of 16 elements, maximum binary search comparisons:', type: 'multiple_choice', options: [{ id: 'a', text: '16' }, { id: 'b', text: '8' }, { id: 'c', text: '5' }, { id: 'd', text: '4' }], correctAnswers: ['c'], explanation: 'log2(16) = 4, plus 1 for final comparison = 5 max.' },
    { text: 'Which list can use binary search directly?', type: 'multiple_choice', options: [{ id: 'a', text: '[5, 2, 8, 1]' }, { id: 'b', text: '[1, 2, 5, 8]' }, { id: 'c', text: '[8, 5, 2, 1]' }, { id: 'd', text: 'Both B and C' }], correctAnswers: ['d'], explanation: 'Both ascending [1,2,5,8] and descending [8,5,2,1] sorted lists work.' },
    { text: 'Binary search finds one occurrence. To find all occurrences:', type: 'multiple_choice', options: [{ id: 'a', text: 'One binary search is enough' }, { id: 'b', text: 'Need to check neighbors after finding one' }, { id: 'c', text: 'Impossible' }, { id: 'd', text: 'Use only linear search' }], correctAnswers: ['b'], explanation: 'After finding one, check adjacent elements for duplicates.' },
    { text: 'Binary search efficiency makes it ideal for:', type: 'multiple_choice', options: [{ id: 'a', text: 'Small unsorted lists' }, { id: 'b', text: 'Large sorted datasets' }, { id: 'c', text: 'Frequently changing lists' }, { id: 'd', text: 'Lists with one element' }], correctAnswers: ['b'], explanation: 'Binary search is most beneficial for large, sorted, stable datasets.' }
  ],
  'aap-3-12': [
    { text: 'A procedure is:', type: 'multiple_choice', options: [{ id: 'a', text: 'A type of variable' }, { id: 'b', text: 'A reusable block of code' }, { id: 'c', text: 'A type of list' }, { id: 'd', text: 'A hardware component' }], correctAnswers: ['b'], explanation: 'Procedures (also called functions) are reusable code blocks.' },
    { text: 'Calling a procedure means:', type: 'multiple_choice', options: [{ id: 'a', text: 'Defining the procedure' }, { id: 'b', text: 'Executing the procedure\'s code' }, { id: 'c', text: 'Deleting the procedure' }, { id: 'd', text: 'Renaming the procedure' }], correctAnswers: ['b'], explanation: 'Calling a procedure runs the code inside it.' },
    { text: 'A parameter is:', type: 'multiple_choice', options: [{ id: 'a', text: 'The result of a procedure' }, { id: 'b', text: 'Input passed to a procedure' }, { id: 'c', text: 'A type of loop' }, { id: 'd', text: 'A comment' }], correctAnswers: ['b'], explanation: 'Parameters are values passed into a procedure when called.' },
    { text: 'What does RETURN do in a procedure?', type: 'multiple_choice', options: [{ id: 'a', text: 'Repeats the procedure' }, { id: 'b', text: 'Sends a value back to the caller' }, { id: 'c', text: 'Prints output' }, { id: 'd', text: 'Creates a variable' }], correctAnswers: ['b'], explanation: 'RETURN sends a value back and exits the procedure.' },
    { text: 'Procedural abstraction means:', type: 'multiple_choice', options: [{ id: 'a', text: 'Using only simple code' }, { id: 'b', text: 'Hiding implementation details behind a procedure name' }, { id: 'c', text: 'Avoiding procedures' }, { id: 'd', text: 'Writing longer code' }], correctAnswers: ['b'], explanation: 'Abstraction hides complexity; you use procedure without knowing details.' },
    { text: 'If PROCEDURE add(a, b) { RETURN a + b }, what is add(3, 5)?', type: 'multiple_choice', options: [{ id: 'a', text: '3' }, { id: 'b', text: '5' }, { id: 'c', text: '8' }, { id: 'd', text: '35' }], correctAnswers: ['c'], explanation: 'The procedure returns 3 + 5 = 8.' },
    { text: 'Why use procedures?', type: 'multiple_select', options: [{ id: 'a', text: 'Code reusability' }, { id: 'b', text: 'Easier maintenance' }, { id: 'c', text: 'Better organization' }, { id: 'd', text: 'Slower execution' }], correctAnswers: ['a', 'b', 'c'], explanation: 'Procedures promote reuse, maintenance, and organization.' },
    { text: 'Arguments are:', type: 'multiple_choice', options: [{ id: 'a', text: 'The values passed when calling a procedure' }, { id: 'b', text: 'The parameter names in the definition' }, { id: 'c', text: 'Return values' }, { id: 'd', text: 'Error messages' }], correctAnswers: ['a'], explanation: 'Arguments are actual values passed; parameters are the variables that receive them.' },
    { text: 'A procedure without RETURN:', type: 'multiple_choice', options: [{ id: 'a', text: 'Cannot exist' }, { id: 'b', text: 'Performs actions but returns no value' }, { id: 'c', text: 'Always causes an error' }, { id: 'd', text: 'Returns 0' }], correctAnswers: ['b'], explanation: 'Procedures can perform actions without returning a value.' },
    { text: 'PROCEDURE greet(name) { DISPLAY("Hello, " + name) }. What does greet("Alice") display?', type: 'multiple_choice', options: [{ id: 'a', text: 'Hello, name' }, { id: 'b', text: 'Hello, Alice' }, { id: 'c', text: 'Alice' }, { id: 'd', text: 'greet' }], correctAnswers: ['b'], explanation: 'The parameter name receives "Alice", so "Hello, Alice" is displayed.' },
    { text: 'A procedure can call:', type: 'multiple_choice', options: [{ id: 'a', text: 'Only itself' }, { id: 'b', text: 'No other procedures' }, { id: 'c', text: 'Other procedures' }, { id: 'd', text: 'Only built-in functions' }], correctAnswers: ['c'], explanation: 'Procedures can call other procedures, enabling modular design.' },
    { text: 'If PROCEDURE square(n) { RETURN n * n }, what is square(4) + square(3)?', type: 'multiple_choice', options: [{ id: 'a', text: '7' }, { id: 'b', text: '12' }, { id: 'c', text: '25' }, { id: 'd', text: '49' }], correctAnswers: ['c'], explanation: 'square(4) = 16, square(3) = 9, sum = 25.' },
    { text: 'The scope of a parameter is:', type: 'multiple_choice', options: [{ id: 'a', text: 'The entire program' }, { id: 'b', text: 'Only inside the procedure' }, { id: 'c', text: 'Only outside the procedure' }, { id: 'd', text: 'In all files' }], correctAnswers: ['b'], explanation: 'Parameters are local to the procedure they are defined in.' },
    { text: 'What happens when a procedure is called?', type: 'multiple_choice', options: [{ id: 'a', text: 'Program ends' }, { id: 'b', text: 'Execution jumps to procedure code, then returns' }, { id: 'c', text: 'Nothing' }, { id: 'd', text: 'Variables are deleted' }], correctAnswers: ['b'], explanation: 'Execution moves to procedure, runs it, then continues from the call point.' },
    { text: 'PROCEDURE max(a, b) { IF a > b { RETURN a } ELSE { RETURN b } }. What is max(7, 3)?', type: 'multiple_choice', options: [{ id: 'a', text: '3' }, { id: 'b', text: '7' }, { id: 'c', text: '10' }, { id: 'd', text: '4' }], correctAnswers: ['b'], explanation: '7 > 3, so return 7.' },
    { text: 'How does procedural abstraction manage complexity?', type: 'multiple_choice', options: [{ id: 'a', text: 'By making code longer' }, { id: 'b', text: 'By letting you use procedures without knowing their implementation' }, { id: 'c', text: 'By removing all procedures' }, { id: 'd', text: 'By adding more variables' }], correctAnswers: ['b'], explanation: 'You can use a procedure by knowing what it does, not how it does it.' },
    { text: 'A procedure that calls itself is:', type: 'multiple_choice', options: [{ id: 'a', text: 'Illegal' }, { id: 'b', text: 'Recursive' }, { id: 'c', text: 'Iterative' }, { id: 'd', text: 'Sequential' }], correctAnswers: ['b'], explanation: 'Recursion is when a procedure calls itself.' },
    { text: 'If PROCEDURE double(x) { RETURN x * 2 }, what is double(double(3))?', type: 'multiple_choice', options: [{ id: 'a', text: '6' }, { id: 'b', text: '12' }, { id: 'c', text: '9' }, { id: 'd', text: '3' }], correctAnswers: ['b'], explanation: 'double(3) = 6, double(6) = 12.' },
    { text: 'Procedures help avoid:', type: 'multiple_choice', options: [{ id: 'a', text: 'Code reuse' }, { id: 'b', text: 'Code duplication' }, { id: 'c', text: 'Comments' }, { id: 'd', text: 'Variables' }], correctAnswers: ['b'], explanation: 'Instead of copying code, call a procedure multiple times.' },
    { text: 'A well-named procedure:', type: 'multiple_choice', options: [{ id: 'a', text: 'Should be as short as possible' }, { id: 'b', text: 'Describes what it does' }, { id: 'c', text: 'Uses random characters' }, { id: 'd', text: 'Should match variable names' }], correctAnswers: ['b'], explanation: 'Good procedure names clearly indicate their purpose.' },
    { text: 'PROCEDURE isEven(n) { RETURN n MOD 2 = 0 }. What is isEven(7)?', type: 'multiple_choice', options: [{ id: 'a', text: 'true' }, { id: 'b', text: 'false' }, { id: 'c', text: '7' }, { id: 'd', text: '1' }], correctAnswers: ['b'], explanation: '7 MOD 2 = 1, which is not 0, so return false.' },
    { text: 'Multiple procedures can have:', type: 'multiple_choice', options: [{ id: 'a', text: 'The same name' }, { id: 'b', text: 'Different names but same parameters' }, { id: 'c', text: 'No parameters' }, { id: 'd', text: 'All of the above' }], correctAnswers: ['d'], explanation: 'Procedures can vary in names, parameters, and can have no parameters.' },
    { text: 'What is output? PROCEDURE test() { DISPLAY("A"); DISPLAY("B") }; test()', type: 'multiple_choice', options: [{ id: 'a', text: 'A' }, { id: 'b', text: 'B' }, { id: 'c', text: 'AB' }, { id: 'd', text: 'test' }], correctAnswers: ['c'], explanation: 'Calling test() displays A then B.' },
    { text: 'A return value can be:', type: 'multiple_select', options: [{ id: 'a', text: 'A number' }, { id: 'b', text: 'A string' }, { id: 'c', text: 'A Boolean' }, { id: 'd', text: 'A list' }], correctAnswers: ['a', 'b', 'c', 'd'], explanation: 'Procedures can return values of any data type.' },
    { text: 'Procedures make code:', type: 'multiple_choice', options: [{ id: 'a', text: 'Harder to test' }, { id: 'b', text: 'Easier to test and debug' }, { id: 'c', text: 'Slower' }, { id: 'd', text: 'Impossible to modify' }], correctAnswers: ['b'], explanation: 'Procedures can be tested independently, simplifying debugging.' }
  ],
  'aap-3-13': [
    { text: 'When developing a procedure, first:', type: 'multiple_choice', options: [{ id: 'a', text: 'Write the code' }, { id: 'b', text: 'Define what the procedure should accomplish' }, { id: 'c', text: 'Test it' }, { id: 'd', text: 'Name it' }], correctAnswers: ['b'], explanation: 'First understand the purpose before writing code.' },
    { text: 'A procedure specification includes:', type: 'multiple_select', options: [{ id: 'a', text: 'What it does' }, { id: 'b', text: 'What inputs it takes' }, { id: 'c', text: 'What it returns' }, { id: 'd', text: 'Who wrote it' }], correctAnswers: ['a', 'b', 'c'], explanation: 'Specification covers purpose, inputs, and outputs.' },
    { text: 'Parameters should be named:', type: 'multiple_choice', options: [{ id: 'a', text: 'Single letters only' }, { id: 'b', text: 'Descriptively to indicate their purpose' }, { id: 'c', text: 'Same as the procedure' }, { id: 'd', text: 'Randomly' }], correctAnswers: ['b'], explanation: 'Descriptive parameter names improve readability.' },
    { text: 'A procedure to calculate area of rectangle needs:', type: 'multiple_choice', options: [{ id: 'a', text: 'One parameter' }, { id: 'b', text: 'Two parameters (length and width)' }, { id: 'c', text: 'Three parameters' }, { id: 'd', text: 'No parameters' }], correctAnswers: ['b'], explanation: 'Area = length × width requires both dimensions.' },
    { text: 'How should procedures be designed for reusability?', type: 'multiple_choice', options: [{ id: 'a', text: 'Make them very specific to one case' }, { id: 'b', text: 'Use parameters for values that might change' }, { id: 'c', text: 'Hardcode all values' }, { id: 'd', text: 'Avoid parameters' }], correctAnswers: ['b'], explanation: 'Parameters allow the same procedure to work with different inputs.' },
    { text: 'Which is a good procedure design practice?', type: 'multiple_choice', options: [{ id: 'a', text: 'One procedure does everything' }, { id: 'b', text: 'Each procedure does one specific task' }, { id: 'c', text: 'Procedures should be as long as possible' }, { id: 'd', text: 'Never use parameters' }], correctAnswers: ['b'], explanation: 'Single responsibility: each procedure does one thing well.' },
    { text: 'To convert temperature from Celsius to Fahrenheit:', type: 'multiple_choice', options: [{ id: 'a', text: 'PROCEDURE toF(c) { RETURN c * 9/5 + 32 }' }, { id: 'b', text: 'PROCEDURE toF() { RETURN 9/5 + 32 }' }, { id: 'c', text: 'PROCEDURE toF(c) { RETURN c }' }, { id: 'd', text: 'PROCEDURE toF(c) { RETURN c - 32 }' }], correctAnswers: ['a'], explanation: 'F = C × 9/5 + 32 is the correct formula.' },
    { text: 'Testing a procedure should include:', type: 'multiple_select', options: [{ id: 'a', text: 'Normal inputs' }, { id: 'b', text: 'Edge cases' }, { id: 'c', text: 'Invalid inputs' }, { id: 'd', text: 'Only one test' }], correctAnswers: ['a', 'b', 'c'], explanation: 'Comprehensive testing covers normal, edge, and invalid cases.' },
    { text: 'A procedure that checks if a number is positive:', type: 'multiple_choice', options: [{ id: 'a', text: 'PROCEDURE isPositive(n) { RETURN n > 0 }' }, { id: 'b', text: 'PROCEDURE isPositive() { RETURN true }' }, { id: 'c', text: 'PROCEDURE isPositive(n) { RETURN n }' }, { id: 'd', text: 'PROCEDURE isPositive(n) { RETURN n < 0 }' }], correctAnswers: ['a'], explanation: 'Check if n > 0 and return the Boolean result.' },
    { text: 'Procedure documentation should describe:', type: 'multiple_choice', options: [{ id: 'a', text: 'Nothing' }, { id: 'b', text: 'Purpose, parameters, and return value' }, { id: 'c', text: 'Only the code' }, { id: 'd', text: 'The programmer\'s name' }], correctAnswers: ['b'], explanation: 'Good documentation explains what the procedure does and how to use it.' },
    { text: 'A procedure with no parameters:', type: 'multiple_choice', options: [{ id: 'a', text: 'Cannot exist' }, { id: 'b', text: 'Can perform actions using no external input' }, { id: 'c', text: 'Must return nothing' }, { id: 'd', text: 'Is always wrong' }], correctAnswers: ['b'], explanation: 'Procedures can work without parameters if no input is needed.' },
    { text: 'To find the absolute value of a number:', type: 'multiple_choice', options: [{ id: 'a', text: 'PROCEDURE abs(n) { IF n < 0 { RETURN -n } ELSE { RETURN n } }' }, { id: 'b', text: 'PROCEDURE abs(n) { RETURN n + n }' }, { id: 'c', text: 'PROCEDURE abs(n) { RETURN 0 }' }, { id: 'd', text: 'PROCEDURE abs(n) { RETURN -n }' }], correctAnswers: ['a'], explanation: 'If negative, negate it; otherwise return as is.' },
    { text: 'Modular design means:', type: 'multiple_choice', options: [{ id: 'a', text: 'Writing all code in one place' }, { id: 'b', text: 'Breaking code into independent procedures' }, { id: 'c', text: 'Avoiding procedures' }, { id: 'd', text: 'Using only variables' }], correctAnswers: ['b'], explanation: 'Modular design creates independent, reusable procedures.' },
    { text: 'A procedure to check if a year is a leap year needs:', type: 'multiple_choice', options: [{ id: 'a', text: 'No parameters' }, { id: 'b', text: 'One parameter (the year)' }, { id: 'c', text: 'Twelve parameters' }, { id: 'd', text: 'Three parameters' }], correctAnswers: ['b'], explanation: 'Only the year is needed to determine if it\'s a leap year.' },
    { text: 'Procedures can improve program:', type: 'multiple_select', options: [{ id: 'a', text: 'Readability' }, { id: 'b', text: 'Maintainability' }, { id: 'c', text: 'Testability' }, { id: 'd', text: 'Complexity unnecessarily' }], correctAnswers: ['a', 'b', 'c'], explanation: 'Good procedures improve readability, maintenance, and testing.' },
    { text: 'A greeting procedure that takes a name and time of day:', type: 'multiple_choice', options: [{ id: 'a', text: 'Needs 0 parameters' }, { id: 'b', text: 'Needs 2 parameters' }, { id: 'c', text: 'Needs 5 parameters' }, { id: 'd', text: 'Cannot be created' }], correctAnswers: ['b'], explanation: 'Two inputs needed: name and time of day.' },
    { text: 'When procedure A calls procedure B, which runs first?', type: 'multiple_choice', options: [{ id: 'a', text: 'A runs completely, then B' }, { id: 'b', text: 'B runs when called, then A continues' }, { id: 'c', text: 'Both run simultaneously' }, { id: 'd', text: 'Neither runs' }], correctAnswers: ['b'], explanation: 'When A calls B, B runs; when B completes, A resumes.' },
    { text: 'To develop a procedure for finding the factorial of n:', type: 'multiple_choice', options: [{ id: 'a', text: 'Use iteration multiplying 1 to n' }, { id: 'b', text: 'Just return n' }, { id: 'c', text: 'Return n + 1' }, { id: 'd', text: 'Use no math' }], correctAnswers: ['a'], explanation: 'Factorial is product of integers from 1 to n.' },
    { text: 'A well-designed procedure should:', type: 'multiple_choice', options: [{ id: 'a', text: 'Do many unrelated things' }, { id: 'b', text: 'Have a clear, focused purpose' }, { id: 'c', text: 'Be as complex as possible' }, { id: 'd', text: 'Never return values' }], correctAnswers: ['b'], explanation: 'Each procedure should have a single, clear purpose.' },
    { text: 'Default parameter values are useful when:', type: 'multiple_choice', options: [{ id: 'a', text: 'Never' }, { id: 'b', text: 'A parameter often has the same value' }, { id: 'c', text: 'You want to confuse users' }, { id: 'd', text: 'Parameters are required' }], correctAnswers: ['b'], explanation: 'Defaults simplify calls when common values are used.' },
    { text: 'Procedure development follows which cycle?', type: 'multiple_choice', options: [{ id: 'a', text: 'Write, forget, repeat' }, { id: 'b', text: 'Design, implement, test, refine' }, { id: 'c', text: 'Test, then design' }, { id: 'd', text: 'Only implement' }], correctAnswers: ['b'], explanation: 'Good development: design, implement, test, and refine.' },
    { text: 'Refactoring a procedure means:', type: 'multiple_choice', options: [{ id: 'a', text: 'Deleting it' }, { id: 'b', text: 'Improving its structure without changing behavior' }, { id: 'c', text: 'Adding bugs' }, { id: 'd', text: 'Renaming variables randomly' }], correctAnswers: ['b'], explanation: 'Refactoring improves code quality while maintaining functionality.' },
    { text: 'A procedure to check password validity should:', type: 'multiple_choice', options: [{ id: 'a', text: 'Return the password' }, { id: 'b', text: 'Return true/false based on criteria' }, { id: 'c', text: 'Return a random number' }, { id: 'd', text: 'Print the password' }], correctAnswers: ['b'], explanation: 'Validation procedures typically return Boolean results.' },
    { text: 'How many parameters is too many?', type: 'multiple_choice', options: [{ id: 'a', text: 'More than 1' }, { id: 'b', text: 'There is no exact number, but fewer is often better' }, { id: 'c', text: 'Always use 10+' }, { id: 'd', text: 'Zero' }], correctAnswers: ['b'], explanation: 'Many parameters may indicate the procedure does too much.' },
    { text: 'Procedures contribute to:', type: 'multiple_choice', options: [{ id: 'a', text: 'Code chaos' }, { id: 'b', text: 'Software engineering best practices' }, { id: 'c', text: 'Slower development only' }, { id: 'd', text: 'More errors' }], correctAnswers: ['b'], explanation: 'Procedures support reusability, abstraction, and maintainability.' }
  ]
};

async function seed() {
  console.log('Seeding Big Idea 3 Part 3 (Topics 3.9-3.13)...\n');
  try {
    for (const topic of topics) {
      const questions = questionsData[topic.id] || [];
      const processedQuestions = questions.map((q, index) => ({
        ...q,
        id: `${topic.id}-q${index + 1}`,
        isCustom: false,
        addedBy: null,
        addedAt: new Date(),
        deactivated: false
      }));

      await db.collection('topics').doc(topic.id).set({
        ...topic,
        questions: processedQuestions,
        createdAt: new Date(),
        updatedAt: new Date()
      });
      console.log(`Created topic: ${topic.name} with ${processedQuestions.length} questions`);
    }
    console.log('\nPart 3 complete!');
  } catch (error) {
    console.error('Error:', error);
    throw error;
  }
}

seed().then(() => process.exit(0)).catch(() => process.exit(1));
